services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - findmydog_network

  redis:
    image: redis:7-alpine
    container_name: findmydog_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - findmydog_network

  web:
    build: .
    container_name: findmydog_web
    env_file:
        - .env 
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 findmydog.wsgi:application
    volumes:
      - ./dog_images:/app/dog_images
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=mydb
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-AIzaSyA2OthPTv9ikCmBAaM37P5qjjY4ay12CWw}
      - AUTO_TRAIN_SECRET=${AUTO_TRAIN_SECRET:-super-secret-key-123}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - findmydog_network

  celery:
    build: .
    container_name: findmydog_celery
    command: celery -A findmydog worker --loglevel=info
    volumes:
      - ./dog_images:/app/dog_images
    environment:
      - DB_NAME=mydb
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - findmydog_network

  celery-beat:
    build: .
    container_name: findmydog_celery_beat
    command: celery -A findmydog beat --loglevel=info
    volumes:
      - ./dog_images:/app/dog_images
    environment:
      - DB_NAME=mydb
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - findmydog_network

  # Service สำหรับ django-crontab (ถ้าต้องการใช้)
  cron:
    build: .
    container_name: findmydog_cron
    user: root
    command: >
      sh -c "
      python manage.py crontab add &&
      cron -f
      "
    volumes:
      - ./dog_images:/app/dog_images
      - ./findmydog:/app/findmydog
    environment:
      - DB_NAME=mydb
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - AUTO_TRAIN_SECRET=${AUTO_TRAIN_SECRET:-super-secret-key-123}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - findmydog_network

networks:
  findmydog_network:
    driver: bridge

volumes:
  pgdata: