# Generated by Django 5.2.6 on 2025-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'สมาชิก'), ('org_admin', 'แอดมินองค์กร')], default='citizen', max_length=20),
        ),
    ]
