# Generated by Django 5.2.6 on 2025-09-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
