# Generated by Django 5.2.6 on 2025-09-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dog_is_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='is_lost',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
