# Generated by Django 5.2.6 on 2025-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_dog_is_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'สมาชิก'), ('adoptive_parents', 'พ่อแม่บุญธรรม'), ('org_admin', 'แอดมินองค์กร')], default='citizen', max_length=20),
        ),
    ]
