# Generated by Django 5.2.6 on 2025-11-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=100, null=True, verbose_name='สายพันธุ์'),
        ),
        migrations.AddField(
            model_name='dog',
            name='distinguishing_marks',
            field=models.TextField(blank=True, verbose_name='ลักษณะ/รอยตำหนิเด่น'),
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('M', 'Male (ตัวผู้)'), ('F', 'Female (ตัวเมีย)')], max_length=1, null=True, verbose_name='เพศ'),
        ),
        migrations.AddField(
            model_name='dog',
            name='primary_color',
            field=models.CharField(max_length=50, null=True, verbose_name='สีหลัก'),
        ),
        migrations.AddField(
            model_name='dog',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='สีรอง'),
        ),
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('S', 'Small (เล็ก)'), ('M', 'Medium (กลาง)'), ('L', 'Large (ใหญ่)')], max_length=1, null=True, verbose_name='ขนาด'),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='น้ำหนัก (กก.)'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='อายุ'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='อาหารที่แพ้'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='favorite_food',
            field=models.TextField(blank=True, null=True, verbose_name='อาหารโปรด'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='is_lost',
            field=models.BooleanField(default=False, null=True, verbose_name='สุนัขหาย'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อสุนัข'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='personality',
            field=models.TextField(blank=True, null=True, verbose_name='นิสัยของสุนัข'),
        ),
    ]
