# Generated by Django 5.2.6 on 2025-11-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_dog_breed_dog_distinguishing_marks_dog_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
    ]
