# Generated by Django 5.2.6 on 2025-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sterilization_date',
            field=models.DateField(blank=True, help_text='ระบุวันที่ดำเนินการล่าสุด', null=True, verbose_name='วันที่ทำหมัน/คุมกำเนิดล่าสุด'),
        ),
        migrations.AddField(
            model_name='dog',
            name='sterilization_status',
            field=models.CharField(choices=[('NO', 'ยังไม่ทำ/ไม่ได้คุมกำเนิด'), ('SURGICAL', 'ทำหมันถาวร (ผ่าตัด)'), ('CHEMICAL', 'คุมกำเนิดชั่วคราว (เช่น ฉีดยาคุม)')], default='NO', help_text='ระบุว่าสุนัขได้ทำหมันหรือคุมกำเนิดแบบใด', max_length=10, verbose_name='สถานะการควบคุมกำเนิด'),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccination_history',
            field=models.CharField(blank=True, default='', help_text='กรอกชื่อวัคซีนที่ฉีดแล้ว โดยคั่นด้วยเครื่องหมายคอมมา (เช่น DHPPL, Rabies)', max_length=255, verbose_name='รายการวัคซีนที่ฉีดแล้ว'),
        ),
    ]
