# Generated by Django 5.2.6 on 2025-11-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dog_sterilization_date_dog_sterilization_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='organization',
            field=models.BooleanField(default=False, null=True, verbose_name='อยู่ในการดูแลของโฮงเกลือหมาหรือไม่'),
        ),
    ]
