# Generated by Django 5.2.6 on 2025-11-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_dog_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='weight',
        ),
    ]
