# Generated by Django 5.2.6 on 2025-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_dog_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('ES', 'Extra Small (เล็กมาก)'), ('S', 'Small (เล็ก)'), ('M', 'Medium (กลาง)'), ('L', 'Large (ใหญ่)'), ('XL', 'Extra Large (ใหญ่มาก)'), ('XXL', 'XX Extra Large (ใหญ่พิเศษ)')], max_length=3, null=True, verbose_name='ขนาด'),
        ),
    ]
