# Generated by Django 5.2.6 on 2025-11-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_dog_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='is_lost',
            field=models.BooleanField(choices=[('LOST', 'สูญหาย'), ('NOTLOST', 'ปกติ')], default=False, null=True, verbose_name='สุนัขหาย'),
        ),
    ]
