# Generated by Django 5.2.6 on 2025-11-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_dog_is_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='is_lost',
            field=models.BooleanField(choices=[('true', 'สูญหาย'), ('false', 'ปกติ')], default='false', null=True, verbose_name='สุนัขหาย'),
        ),
    ]
