# Generated by Django 5.2.6 on 2025-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_dog_is_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='is_lost',
            field=models.BooleanField(default=False, verbose_name='สุนัขหาย'),
        ),
    ]
