# Generated by Django 5.2.6 on 2025-11-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_dog_is_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อข่าวสาร')),
                ('content', models.TextField(verbose_name='รายละเอียดเนื้อหา')),
                ('notification_type', models.CharField(choices=[('ACTIVITY', 'กิจกรรมองค์กร/ทั่วไป'), ('DOG_SPECIFIC', 'ประกาศเฉพาะสุนัข'), ('LOST_DOG', 'สุนัขสูญหาย')], default='ACTIVITY', max_length=20, verbose_name='ประเภทข่าวสาร')),
                ('is_important', models.BooleanField(default=False, verbose_name='สำคัญมาก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/', verbose_name='รูปภาพประกอบ')),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='myapp.dog', verbose_name='สุนัขที่เกี่ยวข้อง')),
                ('organization', models.ForeignKey(blank=True, limit_choices_to={'role': 'org_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='องค์กรผู้ประกาศ')),
            ],
            options={
                'verbose_name': 'ข่าวสาร/การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(auto_now_add=True, verbose_name='วันที่รับดูแล')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_parents', to='myapp.dog', verbose_name='สุนัข')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_dogs', to=settings.AUTH_USER_MODEL, verbose_name='พ่อแม่บุญธรรม')),
            ],
            options={
                'verbose_name': 'พ่อแม่บุญธรรม',
                'unique_together': {('user', 'dog')},
            },
        ),
    ]
