# Generated by Django 5.2.4 on 2025-11-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_notification_adoptionparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notification_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.notification')),
            ],
        ),
    ]
