# Generated by Django 5.2.6 on 2025-11-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notificationimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationImage',
        ),
    ]
